export const FRAMESWEB = {
    "lake": {
        poems: ["В какой начальной школе бытия\nПетлять тропа лесная научилась?",
            "Кто первый обозвал тропу «тропой»?\nНу а дорогу кто назвал «дорогой»?",
            "Кто проторил тропу в моем лесу,\nПока я размышлял о мирозданьи?",
            "Кто надо мной смеялся из кустов,\nКогда тропа закончилась болотом?",
            "Лесной тропы задумчивый изгиб...\nКак он осознает себя изгибом?",
            "Куда я шел по этой узкой тропке?\nТуда, куда в конце концов пришел?",
            "Вся наша жизнь — не эта ли тропа, Ведущая оленей к водопою?",
            "Четвертый раз споткнулся на тропе — \nСвернуть или продолжить путь по лесу?",
            "Двух девушек я встретил по пути...\nНо стала ли тропа моя короче?",
            "На сколько троп я стал вчера богаче,\nблуждая по кирилловским лесам?"],
        images_web: ["https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/2tropa1.jpg",
            "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/2tropa2.jpg",
            "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/2tropa3.jpg",
            "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/2tropa4.jpg",
            "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/2tropa5.jpg",
            "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/2tropa6.jpg",
            "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/2tropa7.jpg",
            "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/2tropa8.jpg",
            "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/2tropa9.jpg",
            "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/2tropa10.jpg"],
    },
    "fog": {
        poems: ["Лесной туман — он думает о лесе?\nА лесу хорошо в лесном тумане?",
            "Когда туман уходит, то на листьях\nЧьи слезы остаются до рассвета?",
            "Когда народ выдумывает сказки,\nСюжеты он берет не из тумана?",
            "Мои слова, завязшие в тумане,\nУслышит ли вечерняя кукушка?",
            "А если я в тумане потеряюсь,\nКто будет мне указывать дорогу?",
            "Зачем туман сегодня эти ели\nОдел в такие странные одежды?",
            "В тумане пень похож на водяного?\nИли под пень работает русалка?",
            "А правда ли, что боги обитают\nВ тумане у подножия Олимпа?",
            "Случайно ли в сентябрьском тумане\nСосна напоминает амазонку?",
            "Уйти в туман — геройство или глупость?\nЯ не пойму: дурак я или витязь?"],
        images_web: ["https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/1tuman1.jpg",
            "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/1tuman2.jpg",
            "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/1tuman3.jpg",
            "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/1tuman4.jpg",
            "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/1tuman5.jpg",
            "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/1tuman6.jpg",
            "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/1tuman7.jpg",
            "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/1tuman8.jpg",
            "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/1tuman9.jpg",
            "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/1tuman10.jpg"],
    },
    "olxon": {
        poems: ["Кто наточил Ольхонские клыки,\nГрызущие байкальские пейзажи?",
            "О чем просил камлающий шаман\nЗадумчивого бога перевала?",
            "Что получил камлающий шаман\nОт своего задумчивого бога?",
            "А прав ли я, бросая пятачок\nВ слепую пасть байкальского бурхана?",
            "Когда тебя причислили к чужим,\nУдобно ли уйти, не попрощавшись?",
            "Когда в Ольхон врезается Сарма,\nНе люди ли — причина урагана?",
            "Кто раздевал ольхонские гольцы?\nКто искривлял ольхонские деревья?",
            "А если я уеду на Ольхон,\nТо кто меня заставит воротиться?",
            "Я осетил священную скалу,\nНо стал ли я от этого счастливей?",
            "Мне кажется, что здесь моя земля?\nИли опять обманывает зренье?"],
        images_web: ["https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/3olkhon1.jpg",
            "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/3olkhon2.jpg",
            "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/3olkhon3.jpg",
            "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/3olkhon4.jpg",
            "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/3olkhon5.jpg",
            "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/3olkhon6.jpg",
            "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/3olkhon7.jpg",
            "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/3olkhon8.jpg",
            "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/3olkhon9.jpg",
            "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/3olkhon10.jpg"],
    },
    "vecher": {
        poems: ["Дым от костра — противник тишины\nИли союзник майского тумана?",
            "Под вечер льют расплавленную медь\nИли меняют золото на небе?",
            "Кто разбросал сосновые стволы\nУ окончанья солнечной дороги?",
            "Я видел, как скончался этот день.\nА он меня заметил перед смертью?",
            "Кто опрокинул солнечный желток\nНа серый круг вечерней сковородки?",
            "Последний луч сентябрьского солнца\nМне подарил не Пабло ли Неруда?",
            "Когда от скал в Байкал сползает тень —\nНе чайки ли зовут ее с собою?",
            "О чем расскажут совы соловьям\nПри встрече солнца с полною луною?",
            "Когда за мной захлопнется туман,\nКто будет разгонять вечерний воздух?",
            "Кто призывает первых комаров\nНа ужин к нашей маленькой палатке?"],
        images_web: ["https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/4vecher1.jpg",
            "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/4vecher2.jpg",
            "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/4vecher3.jpg",
            "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/4vecher4.jpg",
            "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/4vecher5.jpg",
            "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/4vecher6.jpg",
            "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/4vecher7.jpg",
            "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/4vecher8.jpg",
            "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/4vecher9.jpg",
            "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/4vecher10.jpg"],
    },
    "gora": {
        poems: ["Не слишком ли задумчив перевал\nДля камня, снега и тропинки в небо?",
            "За что грызут сентябрьское небо\nВ вечерний час большие зубы гор?",
            "Со зла ли безымянная гора\nВернула мне застенчивое эхо?",
            "А так ли он заманчив — этот снег,\nКак мне вчера под вечер показалось?",
            "Среди красот Саянского хребта\nКакие стоит унести с собою?",
            "Когда в горах сгущается туман,\nНе духи ли выходят на поверхность?",
            "А правда ли, что нынче у вершин\nВсе разговоры — о вчерашнем ветре?",
            "Я все хочу спросить у этих гор —\nНе Рерих ли любимый их художник?",
            "Как олодно в горах по вечерам —\nБыть может, космос в гости к ним приходит?",
            "О чем молчат альпийские луга,\nКогда на них ступают эдельвейсы?"],
        images_web: ["https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/5gora1.jpg",
            "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/5gora2.jpg",
            "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/5gora3.jpg",
            "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/5gora4.jpg",
            "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/5gora5.jpg",
            "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/5gora6.jpg",
            "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/5gora7.jpg",
            "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/5gora8.jpg",
            "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/5gora9.jpg",
            "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/5gora10.jpg"],
    },
    "ytro": {
        poems: ["Какая птица вывела меня\nИз сказочного леса сновидений?",
            "Кто окропил росою этот лес,\nПока я спал в брезентовой палатке?",
            "На сколько дней задержится со мной\nВосторг, меня под утро посетивший?",
            "Скажите, разве это справедливо,\nЧто весь рассвет достался только мне?",
            "Кто научил смешного паука\nСвить паутину на моей палатке?",
            "Кто разогнал мои ночные страхи,\nКто расплескал мою ночную грусть?",
            "Наверняка на небе кто-то есть...\nОткуда же, иначе, это утро?",
            "Я заварил в котле таежный чай...\nЭй, белки! Вы ко мне придете в гости?",
            "Зачем с утра считала мне года\nДалекая таежная кукушка?",
            "Когда я собирался в этот лес,\nНе ангел ли меня держал за шкирку?"],
        images_web: ["https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/6utro1.jpg",
            "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/6utro2.jpg",
            "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/6utro3.jpg",
            "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/6utro4.jpg",
            "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/6utro5.jpg",
            "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/6utro6.jpg",
            "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/6utro7.jpg",
            "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/6utro8.jpg",
            "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/6utro9.jpg",
            "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/6utro10.jpg"],
    },
    "ozero": {
        poems: ["О чем грустит озерная трава\nНа фоне августовского заката?",
            "А если я сегодня не просплю,\nНа сколько рыб уменьшится протока?",
            "Смогли бы мы без леса вдалеке\nУзнать — где нынче озеро, где небо?",
            "Мне кажется или и вправду здесь\nКрупнее комары и кровожадней?",
            "Спят на боку язи и караси?\nА щуки спят с закрытыми глазами?",
            "Сказала ли утятам обо мне\nПод утро мной испуганная утка?",
            "За что меня не любит водяной?\nЗа то, что я смешу его русалок?",
            "Как холодно на озере с утра...\nНе одолжить ли шубу у ондатры?",
            "Как узнают, что скоро улетать,\nКрикливые утиные подростки?",
            "За два часа до утренних лучей\nВсегда ли так неспешно ходит время?"],
        images_web: ["https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/7ozero1.jpg",
            "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/7ozero2.jpg",
            "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/7ozero3.jpg",
            "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/7ozero4.jpg",
            "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/7ozero5.jpg",
            "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/7ozero6.jpg",
            "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/7ozero7.jpg",
            "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/7ozero8.jpg",
            "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/7ozero9.jpg",
            "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/7ozero10.jpg"],
    },
    "baikal": {
        poems: ["А правда ли родиться суждено\nМне тонкою сосною у Байкала?",
            "Кто по утрам, когда природа спит,\nПьет воду из большой байкальской чаши?",
            "Когда во сне мне снится Багульдейка,\nЯ сплю, или как раз наоборот?",
            "Зачем оставил часть своей души\nЯ на камнях Курминского залива?",
            "Вампилов утонул или ушел\nПо звездам на утиную охоту?",
            "Я сам решил приехать на Байкал,\nИли Байкал привел меня за руку?",
            "Когда Култук встречается с Сармой,\nВ Америке рождаются тайфуны?",
            "А вдруг не влезет в фотоаппарат\nВот этот мыс, похожий на часовню?",
            "Когда прибой слизнул мои часы,\nУ времени сменились очертанья?",
            "Когда Господь задумал этот мир,\nОн не с Байкала начал ли творенье?"],
        images_web: ['https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/8bajkal1.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/8bajkal2.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/8bajkal3.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/8bajkal4.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/8bajkal5.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/8bajkal6.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/8bajkal7.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/8bajkal8.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/8bajkal9.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/8bajkal10.jpg'],
    },
    "pole": {
        poems: ["Скажите, не на эти ли поля\nСаврасовские птицы прилетали?",
            "Для тех, кто вырос в Средней полосе,\nПоля вокруг — как для меня Саяны?",
            "Когда стремится к небу колосок,\nОн знает об осеннем увяданье?",
            "Зачем по полю эти облака\nЕдва заметной тенью пробежали?",
            "О чем вчера под ветром волновались\nНа поле вологодские хлеба?",
            "Комбайн убивает эту рожь\nВсе утро, или все-таки спасает?",
            "Как мыши полевые назовут\nВ своих мышиных мифах тракториста?",
            "За что овраг прорезал это поле?\nЗа дело или ради удальства?",
            "Я б на денек махнулся с комбайнером...\nНо сможет ли он написать стихи?",
            "Какой цирюльник сможет это поле\nЗа две недели налысо побрить?"],
        images_web: ['https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/9pole1.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/9pole2.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/9pole3.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/9pole4.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/9pole5.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/9pole6.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/9pole7.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/9pole8.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/9pole9.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/9pole10.jpg'],
    },
    "osen": {
        poems: ["Какую взятку сунуть журавлям,\nЧтобы они на месяц задержались?",
            "Грустит ли поздней осенью медведь,\nУкладываясь спать в своей берлоге?",
            "Находит ли осенняя река\nСмешным кленовых листьев облетанье?",
            "Спросить бы ненароком у груздей –\nНе скучно ли им с грустью рифмоваться?",
            "Когда идут осенние дожди,\nОни всегда наш город выбирают?",
            "Все лето осень прячется в горах...\nВы там ее случайно не встречали?",
            "Когда я шел с корзиною пустой,\nКто мне сказал: «На всех не напасешься»?",
            "Местами дождь... Ну почему все время\nЯ вечно обитаю в тех местах?",
            "Не правда ли, осенние цветы\nНас как-то примиряют с первым снегом?",
            "А видели ли эти снегири\nКогда-нибудь одетые деревья?"],
        images_web: ['https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/10osen1.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/10osen2.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/10osen3.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/10osen4.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/10osen5.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/10osen6.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/10osen7.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/10osen8.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/10osen9.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/10osen10.jpg'],
    },
}