export const FRAMES = {
  "lake": {
    poems: ["В какой начальной школе бытия\nПетлять тропа лесная научилась?",
      "Кто первый обозвал тропу «тропой»?\nНу а дорогу кто назвал «дорогой»?",
      "Кто проторил тропу в моем лесу,\nПока я размышлял о мирозданьи?",
      "Кто надо мной смеялся из кустов,\nКогда тропа закончилась болотом?",
      "Лесной тропы задумчивый изгиб...\nКак он осознает себя изгибом?",
      "Куда я шел по этой узкой тропке?\nТуда, куда в конце концов пришел?",
      "Вся наша жизнь — не эта ли тропа, Ведущая оленей к водопою?",
      "Четвертый раз споткнулся на тропе — \nСвернуть или продолжить путь по лесу?",
      "Двух девушек я встретил по пути...\nНо стала ли тропа моя короче?",
      "На сколько троп я стал вчера богаче,\nблуждая по кирилловским лесам?"],
    images: ["https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/2Tropa012.jpg",
        "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/2Tropa013.jpg",
        "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/2Tropa014.jpg",
        "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/2Tropa015.jpg",
        "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/2Tropa016.jpg",
        "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/2Tropa017.jpg",
        "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/2Tropa018.jpg",
        "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/2Tropa019.jpg",
        "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/2Tropa020.jpg",
        "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/2Tropa021.jpg"],
  },
  "fog": {
    poems: ["Лесной туман — он думает о лесе?\nА лесу хорошо в лесном тумане?",
            "Когда туман уходит, то на листьях\nЧьи слезы остаются до рассвета?",
            "Когда народ выдумывает сказки,\nСюжеты он берет не из тумана?",
            "Мои слова, завязшие в тумане,\nУслышит ли вечерняя кукушка?",
            "А если я в тумане потеряюсь,\nКто будет мне указывать дорогу?",
            "Зачем туман сегодня эти ели\nОдел в такие странные одежды?",
            "В тумане пень похож на водяного?\nИли под пень работает русалка?",
            "А правда ли, что боги обитают\nВ тумане у подножия Олимпа?",
            "Случайно ли в сентябрьском тумане\nСосна напоминает амазонку?",
            "Уйти в туман — геройство или глупость?\nЯ не пойму: дурак я или витязь?"],
    images: ["https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/1Tuman01.jpg",
        "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/1Tuman02.jpg",
        "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/1Tuman03.jpg",
        "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/1Tuman04.jpg",
        "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/1Tuman05.jpg",
        "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/1Tuman06.jpg",
        "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/1Tuman07.jpg",
        "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/1Tuman08.jpg",
        "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/1Tuman09.jpg",
        "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/1Tuman010.jpg"],
  },
  "olxon": {
    poems: ["Кто наточил Ольхонские клыки,\nГрызущие байкальские пейзажи?",
      "О чем просил камлающий шаман\nЗадумчивого бога перевала?",
      "Что получил камлающий шаман\nОт своего задумчивого бога?",
      "А прав ли я, бросая пятачок\nВ слепую пасть байкальского бурхана?",
      "Когда тебя причислили к чужим,\nУдобно ли уйти, не попрощавшись?",
      "Когда в Ольхон врезается Сарма,\nНе люди ли — причина урагана?",
      "Кто раздевал ольхонские гольцы?\nКто искривлял ольхонские деревья?",
      "А если я уеду на Ольхон,\nТо кто меня заставит воротиться?",
      "Я осетил священную скалу,\nНо стал ли я от этого счастливей?",
      "Мне кажется, что здесь моя земля?\nИли опять обманывает зренье?"],
    images: ["https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/3Olhon032.jpg",
        "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/3Olhon033.jpg",
        "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/3Olhon034.jpg",
        "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/3Olhon035.jpg",
        "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/3Olhon036.jpg",
        "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/3Olhon037.jpg",
        "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/3Olhon038.jpg",
        "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/3Olhon039.jpg",
        "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/3Olhon040.jpg",
        "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/3Olhon041.jpg"],
  },
  "vecher": {
    poems: ["Дым от костра — противник тишины\nИли союзник майского тумана?",
      "Под вечер льют расплавленную медь\nИли меняют золото на небе?",
      "Кто разбросал сосновые стволы\nУ окончанья солнечной дороги?",
      "Я видел, как скончался этот день.\nА он меня заметил перед смертью?",
      "Кто опрокинул солнечный желток\nНа серый круг вечерней сковородки?",
      "Последний луч сентябрьского солнца\nМне подарил не Пабло ли Неруда?",
      "Когда от скал в Байкал сползает тень —\nНе чайки ли зовут ее с собою?",
      "О чем расскажут совы соловьям\nПри встрече солнца с полною луною?",
      "Когда за мной захлопнется туман,\nКто будет разгонять вечерний воздух?",
      "Кто призывает первых комаров\nНа ужин к нашей маленькой палатке?"],
    images: ["https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/4Vecher022.jpg",
        "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/4Vecher023.jpg",
        "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/4Vecher024.jpg",
        "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/4Vecher025.jpg",
        "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/4Vecher026.jpg",
        "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/4Vecher027.jpg",
        "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/4Vecher028.jpg",
        "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/4Vecher029.jpg",
        "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/4Vecher030.jpg",
        "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/4Vecher031.jpg"],
  },
  "gora": {
    poems: ["Не слишком ли задумчив перевал\nДля камня, снега и тропинки в небо?",
      "За что грызут сентябрьское небо\nВ вечерний час большие зубы гор?",
      "Со зла ли безымянная гора\nВернула мне застенчивое эхо?",
      "А так ли он заманчив — этот снег,\nКак мне вчера под вечер показалось?",
      "Среди красот Саянского хребта\nКакие стоит унести с собою?",
      "Когда в горах сгущается туман,\nНе духи ли выходят на поверхность?",
      "А правда ли, что нынче у вершин\nВсе разговоры — о вчерашнем ветре?",
      "Я все хочу спросить у этих гор —\nНе Рерих ли любимый их художник?",
      "Как олодно в горах по вечерам —\nБыть может, космос в гости к ним приходит?",
      "О чем молчат альпийские луга,\nКогда на них ступают эдельвейсы?"],
    images: ["https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/5Gora042.jpg",
        "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/5Gora043.jpg",
        "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/5Gora044.jpg",
        "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/5Gora045.jpg",
        "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/5Gora046.jpg",
        "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/5Gora047.jpg",
        "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/5Gora048.jpg",
        "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/5Gora049.jpg",
        "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/5Gora049.jpg",
        "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/5Gora051.jpg"],
  },
  "ytro": {
    poems: ["Какая птица вывела меня\nИз сказочного леса сновидений?",
      "Кто окропил росою этот лес,\nПока я спал в брезентовой палатке?",
      "На сколько дней задержится со мной\nВосторг, меня под утро посетивший?",
      "Скажите, разве это справедливо,\nЧто весь рассвет достался только мне?",
      "Кто научил смешного паука\nСвить паутину на моей палатке?",
      "Кто разогнал мои ночные страхи,\nКто расплескал мою ночную грусть?",
      "Наверняка на небе кто-то есть...\nОткуда же, иначе, это утро?",
      "Я заварил в котле таежный чай...\nЭй, белки! Вы ко мне придете в гости?",
      "Зачем с утра считала мне года\nДалекая таежная кукушка?",
      "Когда я собирался в этот лес,\nНе ангел ли меня держал за шкирку?"],
    images: ["https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/6Ytro052.jpg",
      "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/6Ytro053.jpg",
      "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/6Ytro054.jpg",
      "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/6Ytro055.jpg",
      "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/6Ytro056.jpg",
      "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/6Ytro057.jpg",
      "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/6Ytro058.jpg",
      "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/6Ytro059.jpg",
      "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/6Ytro060.jpg",
      "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/6Ytro061.jpg"],
  },
  "ozero": {
    poems: ["О чем грустит озерная трава\nНа фоне августовского заката?",
      "А если я сегодня не просплю,\nНа сколько рыб уменьшится протока?",
      "Смогли бы мы без леса вдалеке\nУзнать — где нынче озеро, где небо?",
      "Мне кажется или и вправду здесь\nКрупнее комары и кровожадней?",
      "Спят на боку язи и караси?\nА щуки спят с закрытыми глазами?",
      "Сказала ли утятам обо мне\nПод утро мной испуганная утка?",
      "За что меня не любит водяной?\nЗа то, что я смешу его русалок?",
      "Как холодно на озере с утра...\nНе одолжить ли шубу у ондатры?",
      "Как узнают, что скоро улетать,\nКрикливые утиные подростки?",
      "За два часа до утренних лучей\nВсегда ли так неспешно ходит время?"],
    images: ["https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/7Ozero062.jpg",
      "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/7Ozero063.jpg",
      "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/7Ozero064.jpg",
      "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/7Ozero065.jpg",
      "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/7Ozero066.jpg",
      "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/7Ozero067.jpg",
      "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/7Ozero068.jpg",
      "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/7Ozero069.jpg",
      "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/7Ozero070.jpg",
      "https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/7Ozero071.jpg"],
  },
  "baikal": {
    poems:  ["А правда ли родиться суждено\nМне тонкою сосною у Байкала?",
            "Кто по утрам, когда природа спит,\nПьет воду из большой байкальской чаши?",
            "Когда во сне мне снится Багульдейка,\nЯ сплю, или как раз наоборот?",
            "Зачем оставил часть своей души\nЯ на камнях Курминского залива?",
            "Вампилов утонул или ушел\nПо звездам на утиную охоту?",
            "Я сам решил приехать на Байкал,\nИли Байкал привел меня за руку?",
            "Когда Култук встречается с Сармой,\nВ Америке рождаются тайфуны?",
            "А вдруг не влезет в фотоаппарат\nВот этот мыс, похожий на часовню?",
            "Когда прибой слизнул мои часы,\nУ времени сменились очертанья?",
            "Когда Господь задумал этот мир,\nОн не с Байкала начал ли творенье?"],
    images: ['https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/8Baikal072.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/8Baikal073.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/8Baikal074.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/8Baikal075.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/8Baikal076.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/8Baikal077.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/8Baikal078.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/8Baikal079.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/8Baikal080.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/8Baikal081.jpg'],
  },
  "pole": {
    poems:  ["Скажите, не на эти ли поля\nСаврасовские птицы прилетали?",
            "Для тех, кто вырос в Средней полосе,\nПоля вокруг — как для меня Саяны?",
            "Когда стремится к небу колосок,\nОн знает об осеннем увяданье?",
            "Зачем по полю эти облака\nЕдва заметной тенью пробежали?",
            "О чем вчера под ветром волновались\nНа поле вологодские хлеба?",
            "Комбайн убивает эту рожь\nВсе утро, или все-таки спасает?",
            "Как мыши полевые назовут\nВ своих мышиных мифах тракториста?",
            "За что овраг прорезал это поле?\nЗа дело или ради удальства?",
            "Я б на денек махнулся с комбайнером...\nНо сможет ли он написать стихи?",
            "Какой цирюльник сможет это поле\nЗа две недели налысо побрить?"],
    images: ['https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/9Pole082.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/9Pole083.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/9Pole084.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/9Pole085.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/9Pole086.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/9Pole087.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/9Pole088.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/9Pole089.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/9Pole090.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/9Pole091.jpg'],
  },
  "osen": {
    poems: ["Какую взятку сунуть журавлям,\nЧтобы они на месяц задержались?",
            "Грустит ли поздней осенью медведь,\nУкладываясь спать в своей берлоге?",
            "Находит ли осенняя река\nСмешным кленовых листьев облетанье?",
            "Спросить бы ненароком у груздей –\nНе скучно ли им с грустью рифмоваться?",
            "Когда идут осенние дожди,\nОни всегда наш город выбирают?",
            "Все лето осень прячется в горах...\nВы там ее случайно не встречали?",
            "Когда я шел с корзиною пустой,\nКто мне сказал: «На всех не напасешься»?",
            "Местами дождь... Ну почему все время\nЯ вечно обитаю в тех местах?",
            "Не правда ли, осенние цветы\nНас как-то примиряют с первым снегом?",
            "А видели ли эти снегири\nКогда-нибудь одетые деревья?"],
    images: ['https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/10Osen092.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/10Osen093.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/10Osen094.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/10Osen095.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/10Osen096.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/10Osen097.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/10Osen098.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/10Osen099.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/10Osen0100.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/10Osen0101.jpg'],
  },
  "dozhd": {
    poems: ["Под этим нескончаемым дождем\nКак чувствуют себя ромашки в поле?",
            "Не от моей ли скуки завелись\nНа майском небе сумрачные тучи?",
            "Ну, сколько можно думать о дожде,\nЗастывшем между вторником и маем?",
            "Ну, кто со мной сегодня под дождем?\nУжели только галки и вороны?",
            "Промокло все: и куртка, и душа...\nОткуда же взялись сухие мысли?",
            "Кто изобрел осенние дожди?\nКакой небесный гений авангарда?",
            "А радуга — она была всегда\nИли была подарена Адаму?",
            "А может ли компьютер сосчитать\nКоличество дождинок в этом ливне?",
            "Не правда ли, в окно смотреть на дождь\nПриятнее, чем, скажем, из палатки?",
            "Успела ли очнуться от дождя\nПридавленная радугой равнина?"],
    images: ['https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/11Dozhd0102.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/11Dozhd0103.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/11Dozhd0194.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/11Dozhd0195.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/11Dozhd0196.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/11Dozhd0197.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/11Dozhd0198.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/11Dozhd0199.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/11Dozhd0200.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/11Dozhd0201.jpg'],

  },
  "christmas": {
    poems: ["У ангела — зеленые крыла?\nИли сегодня прилетал не ангел?",
            "Кого искал рождественский мороз\nВ микрорайоне нашем по подъездам?",
            "Когда встречает ангел Дед Мороза,\nО чем они весь вечер говорят?"],
    images: ['https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/13Christmas0184.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/13Christmas0185.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/13Christmas0186.jpg'],
  },
  "oblaka": {
    poems: ["С чего решили эти облака,\nЧто я устал от солнечной погоды?",
            "Сумеет ли дождливая весна\nПерерасти в безоблачную осень?",
            "Сбиваются ли в стаи облака,\nКогда плывут за птицами на север?",
            "Кто ощипал небесного гуся?\nНе праздник ли сегодня там, на небе?",
            "За перевалом облачной гряды\nЗовется как небесная равнина?",
            "Не в облаках ли обрели покой\nЗабытые языческие боги?",
            "Скажите, если не было дождя,\nЗачем на небе тучи собирались?",
            "Вернутся ли на север облака\nИз этой бесконечной кругосветки?",
            "Кто на закате проливает кровь\nЧетвертый день на облачную скатерть?"],
    images: ['https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/16Oblaka0174.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/16Oblaka0175.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/16Oblaka0176.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/16Oblaka0177.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/16Oblaka0178.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/16Oblaka0179.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/16Oblaka0180.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/16Oblaka0181.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/16Oblaka0182.jpg'],
  },
  "venece": {
    poems: ["А стоит ли Венеция того,\nЧтоб тут поэтов русских хоронили?",
            "За что же итальянцы нарекли\nИзогнутую лодочку «гондолой»?",
            "Не здесь ли разводили в старину\nСварливые алхимики русалок?",
            "Кто в море погружает день за днем\nЗадумчивый собор Святого Марка?",
            "А если этот город уплывет,\nЕвропа без него осиротеет?"],
    images: ['https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/17Venece0104.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/17Venece0105.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/17Venece0106.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/17Venece0107.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/17Venece0108.jpg'],
  },
  "dvoe": {
    poems: ["Когда фотограф нас запечатлел,\nМы собирались жить на снимке вечно?",
            "Ах, почему же так недолговечны\nСлова, цветы и вечная любовь?",
            "Где обитает прошлая любовь?\nНельзя ли с ней однажды созвониться?"],
    images: ['https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/19DVOE0124.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/19DVOE0125.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/19DVOE0126.jpg'],
  },
  "dom": {
    poems: ["О чем всю ночь шепталась с домовым\nНа кухне наша маленькая кошка?",
            "Весной сирень у нас не расцвела...\nЕе мы недостаточно любили?",
            "Когда жильцы в кроватях видят сны,\nДома друг друга водят на прогулку?"],
    images: ['https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/20Dom0144.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/20Dom0145.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/20Dom0146.jpg'],
  },
  "prud": {
    poems: ["Когда лягушки квакают, они\nПоют или ругаются с гусями?",
            "Как часто звезды смотрят в этот пруд\nВо время расцветания кувшинок?",
            "А осенью, когда идут дожди,\nСтрадают ли лягушки ревматизмом?",
            "Научит ли когда-нибудь утят\nЛюбить свой пруд стареющая утка?",
            "Не здесь ли пилигримы-облака\nПо вечерам в осоке отдыхают?",
            "Куда плывет беспечный головастик?\nИскать себя? Или себе подобных?"],
    images: ['https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/21Prud0154.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/21Prud0155.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/21Prud0156.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/21Prud0157.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/21Prud0158.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/21Prud0160.jpg'],
  },
  "tramvai": {
    poems: ["Когда я ем счастливые билеты,\nОткуда счастье смотрит на меня?",
            "Скажите, я доеду до кольца,\nИли трамвай уходит в бесконечность?",
            "О чем грустит задумчивый трамвай,\nКогда встречает ветреный троллейбус?"],
    images: ['https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/22Tramvai0164.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/22Tramvai0165.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/22Tramvai0166.jpg'],
  },
  "more": {
    poems: ["А помнит ли алуштинский песок\nСтупней моих тяжелых очертанья?",
            "Кто по ночам командует приливом?\nЯ, или одинокая луна?",
            "Живу в Крыму. Вы чувствуете, как\nОт этих слов повеяло прибоем?",
            "За что весь день гранитный парапет\nПощечины от моря получает?",
            "Шаланды на песчаном берегу\nПечалятся о пойманной кефали?",
            "Ну почему всегда вокруг меня\nТолпою собираются медузы?",
            "Кого искал все утро этот краб?\nМеня, или пропавшую подругу?"],
    images: ['https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/23More0202.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/23More0203.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/23More0294.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/23More0295.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/23More0296.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/23More0297.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/23More0298.jpg'],
  },
  "vesna": {
    poems: ["А, может быть, нуждается в леченьи\nПрирода, заболевшая весной?",
            "Стесняются ли мартовские липы\nВ лесу своей весенней наготы?",
            "Когда медведь вылазит из берлоги,\nОн рад тому, что кончилась зима?",
            "Не больно ли весенним облакам,\nКогда деревья в них вонзают ветви?",
            "Прощают ли весной сухие пни\nЖивым деревьям летние обиды?",
            "Куда текут весенние ручьи?\nО чем грустят последние синицы?",
            "Кто укололся ежиком травы?\nКто за апрель платил деньгами листьев?",
            "Не знаете случайно, для кого\nВчера расцвет багульник на болоте?",
            "Чем кончилась весенняя капель?\nКакая капля в ней была последней?"],
    images: ['https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/24Vesna0284.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/24Vesna0285.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/24Vesna0286.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/24Vesna0287.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/24Vesna0288.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/24Vesna0289.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/24Vesna0290.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/24Vesna0291.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/24Vesna0292.jpg',],
  },
  "reka": {
    poems: ["Вы знаете, что горная река\nДля человека — лучший собеседник?",
            "Кому передавали ледники\nС рекой свои холодные приветы?",
            "Старалась ли таежная природа\nПридать реке такой красивый вид?",
            "Зачем пыталась перекуковать\nШум водопада глупая кукушка?",
            "К кому плывет стремительный таймень,\nСражаясь героически с теченьем?",
            "Когда туман касается воды,\nНе небо ли спускается на землю?",
            "Осенний лист, плывущий по реке,\nМечтает ли доплыть до океана?",
            "Когда мне снится горная река,\nХочу ли я проснуться на равнине?",
            "Вся жизнь моя — кипящий водопад...\nКак починить разбитые байдарки?"],
    images: ['https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/25Reka0274.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/25Reka0275.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/25Reka0276.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/25Reka0277.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/25Reka0278.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/25Reka0279.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/25Reka0280.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/25Reka0281.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/25Reka0282.jpg'],
  },
  "vrema": {
    poems: ["Безвременье, ты только для меня,\nИли никто часов не наблюдает?",
            "Года между рождением и смертью\nЗовутся жизнью или суетой?",
            "Кукушка, что кукует каждый час,\nВам иногда не кажется ехидной?",
            "Какой дурак будильник изобрел?\nНаверное, сторонник мазохизма?",
            "А хочешь, я куплю секундомер,\nЧтоб воровать у времени секунды?"],
    images: ['https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/27Vrema0204.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/27Vrema0205.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/27Vrema0206.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/27Vrema0207.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/27Vrema0208.jpg'],
  },
  "son": {
    poems: ["Вращается ли в космосе Земля,\nПока я сплю в купе на верхней полке?",
            "Зимой, когда медведю снятся сны,\nОни клубятся над его берлогой?",
            "А может быть, кому-нибудь и я\nПопробую присниться этой ночью?.."],
    images: ['https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/28Son0214.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/28Son0215.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/28Son0216.jpg'],
  },
  "derevna": {
    poems: ["Куда плывут сибирские деревни\nПо морю свежевспаханных полей?",
            "Цветение картофельных полей —\nИскусство или что-то прикладное?",
            "Скажите мне, пшеничные поля,\nВам не хватает русского Ван-Гога?",
            "Где летом обитает домовой?\nНа сеновале? В бане? За колодцем?",
            "Я бы пошел работать пастухом,\nНо кто же мне доверит это стадо?"],
    images: ['https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/29Derevna0234.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/29Derevna0235.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/29Derevna0236.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/29Derevna0237.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/29Derevna0238.jpg'],
  },
  "gorod": {
    poems: ["Какую рыбу хочет изловить\nМостов и улиц сетью этот город?",
            "Скучает ли гранитная река\nО навсегда потерянной свободе?",
            "Что ищут утром толпы горожан?\nВчерашний день? Утраченную радость?",
            "Кто черпал из колодезных дворов\nСвятую воду русского искусства?",
            "А остро ли наточен нож реки,\nРассекший этот город на две части?",
            "На город надвигается зима...\nНельзя ли ее как-то отодвинуть?",
            "Мне светофор командует: «иди»!\nКуда идти? В котором направленьи?"],
    images: ['https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/30Gorod0244.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/30Gorod0245.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/30Gorod0246.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/30Gorod0247.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/30Gorod0248.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/30Gorod0249.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/30Gorod0250.jpg'],
  },
  "sumerki": {
    poems: ["О чем мечтает сумеречный лес,\nВпечатанный в сентябрьское небо?",
            "Из сумерек доносится вопрос:\n«Куда же ты собрался на ночь глядя?»",
            "Не правда ли, чуть-чуть тревогой веет\nОт вечера, что нынче наступил?",
            "За что сегодня эти фонари\nИзмучили огнем вечерний сумрак?",
            "Кто целый час смеркал окрестный вид?\nЧто именно вокруг меня смеркалось?",
            "Не правда ли, вечерняя луна\nНа девочку невинную похожа?",
            "Кто заливает тушью облака\nЗа полчаса до наступленья ночи?",
            "Не скучно ли по вечерам плащу,\nЗабытому на даче под навесом?",
            "Похожи ли под вечер комары\nНа пепел от сгоревшего заката?",
            "Скажите, как луне не надоест\nТорить в озерах лунную дорожку?"],
    images: ['https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/31Sumerki0254.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/31Sumerki0255.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/31Sumerki0256.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/31Sumerki0257.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/31Sumerki0258.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/31Sumerki0259.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/31Sumerki0260.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/31Sumerki0261.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/31Sumerki0262.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/31Sumerki0263.jpg'],
  },
  "fonari": {
    poems: ["Ругается ли уличный фонарь\nНа скверные собачьи повадки?",
            "А так ли он уютен, этот город,\nКак думают фонарные столбы?",
            "А, может, были эти фонари\nВ ином существованьи моряками?",
            "Мечтают ли фонарные столбы\nПопасть в холодный мир полярной ночи?",
            "Чугунный штырь фонарного столба\nНе родственник ли знака восклицанья?",
            "Скажи, ты навсегда остолбенел,\nФонарный столб на улице Проезжей?",
            "За что нас осветили фонари,\nКогда мы в полумраке целовались?",
            "Как смотрят городские фонари\nНа фонари промышленных окраин?",
            "Ну что вам рассказать о фонарях...\nВам интересно, кто их выключает?"],
    images: ['https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/32Fonari0264.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/32Fonari0265.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/32Fonari0266.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/32Fonari0267.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/32Fonari0268.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/32Fonari0269.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/32Fonari0270.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/32Fonari0271.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/32Fonari0272.jpg'],
  },
  "cherepovets": {
    poems: ["15 фонарей или 16\nОт булочной до дома моего?",
            "А если проиграет «Северсталь»,\nВас посетят мгновенья светлой грусти?"],
    images: ['https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/33Cherepovets0302.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/33Cherepovets0303.jpg'],
  },
  "ludi": {
    poems: ["Достойна ли властителя умов\nПустая перебранка в магазине?",
            "Как попадают в мир очередей?\nИ часто ль возвращаются обратно?"],
    images: ['https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/34Ludi0324.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/34Ludi0325.jpg'],
  },
  "musli": {
    poems: ["Застенчивость всегда стоит за стенкой?\nУ подлости всегда косой прищур?",
            "Когда добро приходит с кулаками,\nсамозащита не запрещена?"],
    images: ['https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/35Musli0314.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/35Musli0316.jpg'],
  },
  "taiga": {
    poems: ["О чем грустит задумчивый кедрач,\nБредущий по ноябрьскому снегу?",
            "А знает ли таежное шоссе\nО том, как по утрам оно красиво?",
            "А сколько их - таежных деревень,\nРаскиданных по маленьким распадкам?",
            "А помнит ли байкальская тайга\nО том, что я в ней как-то заблудился?",
            "А правда ли, что лешие в тайге\nПо вечерам играют на гитаре?"],
    images: ['https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/36Taiga0304.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/36Taiga0305.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/36Taiga0306.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/36Taiga0307.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/36Taiga0308.jpg'],
  },
  "semia": {
    poems: ["Вы знаете, что счастье пахнет детством?\nТак почему же нет у вас детей?",
            "Кто изобрел семейные проблемы?\nИ получил ли он на них патент?",
            "А если «я» у нас всего четыре,\nТо верно ли название - «семья»?"],
    images: ['https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/38Semia0342.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/38Semia0343.jpg',
            'https://cdn.sberdevices.ru/temp/sberfriend/RestMinutes/38Semia0344.jpg'],
  },
 }